language: node_js
node_js:
- '5'
before_install:
- bash scripts/deploy.sh
- rvm install 2.2.2
install:
- npm install
- bundle install
script: npm run build
deploy:
  provider: script
  script: bash scripts/deploy.sh
  skip_cleanup: true
  on:
    branch: master
