language: node_js
node_js:
- '5'
before_install:
- openssl aes-256-cbc -K $encrypted_e28bee3cc358_key -iv $encrypted_e28bee3cc358_iv
  -in travis-deploy.enc -out ~\/.ssh/travis-deploy -d
- rvm install 2.2.2
install:
- npm install
- bundle install
script: npm run build
deploy:
  provider: script
  script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/_site root@159.203.228.62:/var/www/html
  skip_cleanup: true
  on:
    branch: master
